# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Apache Lucene and Solr open-source search software"
  homepage: https://lucene.apache.org/
  labels:
    - lucene
    - solr
    - search
    - nosql
    - java
    - backend
    - search-engine
    - information-retrieval

  enabled_merge_buttons:
    squash: true
    merge:  false
    rebase: false

notifications:
  commits:      commits@lucene.apache.org
  issues:       issues@lucene.apache.org
  pullrequests: issues@lucene.apache.org
  jira_options: link label worklog
