sonar.projectKey=lucene-solr
sonar.projectName=lucene-solr
sonar.projectVersion=1.0

sonar.links.scm=https://github.com/Unity-Technologies/lucene-solr
sonar.pullrequest.github.repository=Unity-Technologies/lucene-solr
sonar.exclusions=**/*.test.js,frontend_tests/**,docs/**