#!/bin/bash
#
# Copyright 2006 The Apache Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Shell script to make an Atomic Backup after Commit of
# a Solr Lucene collection.

orig_dir=$(pwd)
cd ${0%/*}/..
solr_root=$(pwd)
cd ${orig_dir}

unset solr_port data_dir user verbose
. ${solr_root}/bin/scripts-util

# set up variables
prog=${0##*/}
log=${solr_root}/logs/${prog}.log

# define usage string
USAGE="\
usage: $prog [-p port] [-d dir] [-u username] [-v]
       -p          specify Solr port number
       -d          specify directory holding index data
       -u          specify user to sudo to before running script
       -v          increase verbosity
"

# parse args
while getopts p:d:u:v OPTION
do
    case $OPTION in
    p)
        solr_port="$OPTARG"
        ;;
    d)
        data_dir="$OPTARG"
        ;;
    u)
        user="$OPTARG"
        ;;
    v)
        verbose="v"
        ;;
    *)
        echo "$USAGE"
        exit 1
    esac
done

if [[ -z ${solr_port} ]]
then
    echo "Solr port number missing in $confFile or command line."
    echo "$USAGE"
    exit 1
fi

# user default value for data_dir if not specified
# relative path starts at ${solr_root}
if [[ -z ${data_dir} ]]
then
    data_dir=${solr_root}/data
elif [[ "`echo ${data_dir}|cut -c1`" != "/" ]]
then
    data_dir=${solr_root}/${data_dir}
fi

fixUser "$@"

start=`date +"%s"`

logMessage started by $oldwhoami
logMessage command: $0 $@

logMessage sending commit to Solr server at port ${solr_port}
rs=`curl http://localhost:${solr_port}/update -s -d "<commit/>"`
if [[ $? != 0 ]]
then
  logMessage failed to connect to Solr server at port ${solr_port}
  logMessage commit failed
  logExit failed 1
fi

# check status of commit request
rc=`echo $rs|cut -f2 -d'"'`
if [[ $? != 0 ]]
then
  logMessage commit request to Solr at port ${solr_port} failed:
  logMessage $rs
  logExit failed 2
fi

# successful commit creates a snapshot file synchronously
lastsnap=`ls -drt1 ${data_dir}/snapshot.* 2> /dev/null | tail -1 `

if [[ $lastsnap == "" ]]
then
  logMessage commit did not create snapshot at port ${solr_port}; backup failed:
  logExit failed 3
fi

name=backup.${lastsnap##*snapshot.}
temp=temp-${name}

if [[ -d ${data_dir}/${name} ]]
then
    logMessage backup directory ${data_dir}/${name} already exists
    logExit aborted 1
fi

if [[ -d ${data_dir}/${temp} ]]
then
    logMessage backingup of ${data_dir}/${name} in progress
    logExit aborted 1
fi
logMessage making backup ${data_dir}/${name}

# clean up after INT/TERM
trap 'echo cleaning up, please wait ...;/bin/rm -rf ${data_dir}/${name} ${data_dir}/${temp};logExit aborted 13' INT TERM

# make a backup using hard links into temporary location
# then move it into place atomically
cp -lr ${lastsnap} ${data_dir}/${temp}
mv ${data_dir}/${temp} ${data_dir}/${name}

logExit ended 0
