SOLRB_VERSION = '0.0.1'

require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/packagetask'
require 'rake/gempackagetask'

task :default => [:test]

Rake::TestTask.new('test') do |t|
  t.libs << 'lib'
  t.pattern = 'test/*_test.rb'
  t.verbose = true
  t.ruby_opts = ['-r solr', '-r test/unit']
end

spec = Gem::Specification.new do |s|
  s.name = 'solr'
  s.version = SOLRB_VERSION
  s.author = 'Apache Solr'
  s.email = 'solr-user@lucene.apache.org'
  s.homepage = 'http://wiki.apache.org/solr/Flare'
  s.platform = Gem::Platform::RUBY
  s.summary = 'A ruby library for working with Apache Solr'
  s.files = Dir.glob("{lib,test}/**/*")
  s.require_path = 'lib'
  s.autorequire = 'solr'
  s.has_rdoc = true
  
#  s.test_file = 'test/ts_solr.rb'
#  s.bindir = 'bin'
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end

Rake::RDocTask.new('doc') do |rd|
  rd.rdoc_files.include("lib/**/*.rb")
  rd.main = 'Solr::Connection'
  rd.rdoc_dir = 'doc'
end
