= Audit Logging
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr has the ability to log an audit trail of all events in the system.
Audit loggers are pluggable to suit any possible format or log destination.

[quote]
An audit trail (also called audit log) is a security-relevant chronological record, set of records, and/or destination and source of records that provide documentary evidence of the sequence of activities that have affected at any time a specific operation, procedure, or event. (https://en.wikipedia.org/wiki/Audit_trail[Wikipedia])

== Event types
These are the event types triggered by the framework:

[%header,format=csv,separator=;]
|===
EventType;Usage
AUTHENTICATED;User successfully authenticated
REJECTED;Authentication request rejected
ANONYMOUS;Request proceeds with unknown user
ANONYMOUS_REJECTED;Request from unknown user rejected
AUTHORIZED;Authorization succeeded
UNAUTHORIZED;Authorization failed
COMPLETED;Request completed successfully
ERROR;Request was not executed due to an error
|===

By default only the final event types `REJECTED`, `ANONYMOUS_REJECTED`, `UNAUTHORIZED`, `COMPLETED` and `ERROR` are logged.

== Configuration in security.json
Audit logging is configured in `security.json` under the `auditlogging` key.

The example `security.json` below configures synchronous audit logging to Solr default log file. 

[source,json]
----
{
  "auditlogging":{
     "class": "solr.SolrLogAuditLoggerPlugin"
  }
}
----

To make audit logging happen asynchronously in the backgroun, add the parameter `async: true`. This will cause the events to be put on a queue for asynchronous logging by one or more background threads. You may optionally also configure queue size, number of threads and whether it should block when the queue is full or discard events.

[source,json]
----
{
  "auditlogging":{
     "class": "solr.SolrLogAuditLoggerPlugin",
     "async": true,
     "blockAsync" : false,
     "numThreads" : 2,
     "queueSize" : 4096
  }
}
----

The defaults are `async: false`, `blockAsync: false`, `queueSize: 4096` and `numThreads: 2`.

=== Chaining multiple loggers
Using the `MultiDestinationAuditLogger` you can configure multiple audit logger plugins in a chain, to log to multiple destinations, as follows:

[source,json]
----
{
  "auditlogging":{
     "class" : "solr.MultiDestinationAuditLogger",
     "plugins" : [
       { "class" : "solr.SolrLogAuditLoggerPlugin" },
       { "class" : "solr.MyOtherAuditPlugin",
         "customParam" : "value"
       }
     ]
  }
}
----

== Metrics
AuditLoggerPlugins record metrics about count and timing of log requests, as well as queue size for async loggers.