= Circuit Breakers
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr's circuit breaker infrastructure allows prevention of actions that can cause a node to go beyond its capacity or to go down. The
premise of circuit breakers is to ensure a higher quality of service and only accept request loads that are serviceable in the current
resource configuration.

== When To Use Circuit Breakers
Circuit breakers should be used when the user wishes to trade request throughput for a higher Solr stability. If circuit breakers
are enabled, requests may be rejected under the condition of high node duress with an appropriate HTTP error code (typically 503).

It is up to the client to handle this error and potentially build a retrial logic as this should ideally be a transient situation.

== Circuit Breaker Configurations
The following flag controls the global activation/deactivation of circuit breakers. If this flag is disabled, all circuit breakers
will be disabled globally. Per circuit breaker configurations are specified in their respective sections later.

[source,xml]
----
<useCircuitBreakers>false</useCircuitBreakers>
----

This flag acts as the highest authority and global controller of circuit breakers. For using specific circuit breakers, each one
needs to be individually enabled in addition to this flag being enabled.

== Currently Supported Circuit Breakers

=== JVM Heap Usage Based Circuit Breaker
This circuit breaker tracks JVM heap memory usage and rejects incoming search requests with a 503 error code if the heap usage
exceeds a configured percentage of maximum heap allocated to the JVM (-Xmx). The main configuration for this circuit breaker is
controlling the threshold percentage at which the breaker will trip.

To enable/disable JVM heap usage based circuit breaker, use the following configuration:

[source,xml]
----
<isMemoryCircuitBreakerEnabled>true</isMemoryCircuitBreakerEnabled>
----

Note that this configuration will be overridden by the global circuit breaker flag -- if circuit breakers are disabled, this flag
will not help you.

To set the triggering threshold as a percentage of the max heap allocated to the JVM, use the following parameter.

[source,xml]
----
<memoryCircuitBreakerThresholdPct>75</memoryCircuitBreakerThresholdPct>
----
It does not logically make sense to have a threshold below 50% and above 95% of the max heap allocated to the JVM. Hence, the range
of valid values for this parameter is [50, 95], both inclusive.

Consider the following example:

JVM has been allocated a maximum heap of 5GB (-Xmx) and memoryCircuitBreakerThresholdPct is set to 75. In this scenario, the heap usage
at which the circuit breaker will trip is 3.75GB.


=== CPU Utilization Based Circuit Breaker
This circuit breaker tracks CPU utilization and triggers if the average CPU utilization over the last minute
exceeds a configurable threshold.

To enable/disable CPU utilization based circuit breaker, use the following configuration:

[source,xml]
----
<isCpuCircuitBreakerEnabled>true</isCpuCircuitBreakerEnabled>
----

Note that this configuration will be overridden by the global circuit breaker flag -- if circuit breakers are disabled, this flag
will not help you.

To set the triggering threshold in CPU utilization percentage, use the following parameter.
[source,xml]
----
<cpuCircuitBreakerThresholdPct>75</cpuCircuitBreakerThresholdPct>
----
The range of valid values for this parameter is [40, 95], both inclusive.

Note that both these circuit breakers are checked for each incoming search request and consider the current heap usage of the node and average CPU usage over the last minute, respectively.
The checks does not impact performance, but any performance regressions that are suspected to be caused by this feature should be reported to the dev list.

== Performance Considerations
It is worth noting that while JVM or CPU circuit breakers does not add any noticeable overhead per query, having too many
circuit breakers checked for a single request can cause a performance overhead.

In addition, it is a good practice to exponentially back off while retrying requests on a busy node.

