= How to Contribute to Solr Documentation
:page-tocclass: right
:page-toclevels: 2
:page-shortname: how-to-contribute
:page-permalink: how-to-contribute.html

The Lucene/Solr project has made it easy for anyone to contribute to the Solr Reference Guide with a patch.

The Guide is written in simple AsciiDoc-formatted files, and the source lives in the main Lucene/Solr source repository, right alongside the code.

ifdef::backend-pdf[]
See the latest information on how to contribute to documentation online at https://lucene.apache.org/solr/guide/meta-docs.html.
endif::[]

ifdef::backend-html5[]
The following sections give an overview of how to work with AsciiDoc-format files, how our documentation is generated, and how to do a Ref Guide release.

Once you have a patch you'd like to contribute, you can submit it with a JIRA issue, the same as any other patch. See also the Solr wiki section on https://wiki.apache.org/solr/HowToContribute[How To Contribute] for information on submitting patches.

== Working with AsciiDoc Files
include::meta-docs/asciidoc-syntax.adoc[leveloffset=+2]

include::meta-docs/editing-tools.adoc[leveloffset=+2]

== Modifying the Output Formats
The Solr Reference Guide is published in two formats, HTML and PDF. Different tools are used for each.
include::meta-docs/jekyll.adoc[leveloffset=+2]

include::meta-docs/pdf.adoc[leveloffset=+2]

== Building & Publishing the Guide
include::meta-docs/publish.adoc[leveloffset=+2]
endif::[]
