= JWT Authentication Plugin
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr can support https://en.wikipedia.org/wiki/JSON_Web_Token[JSON Web Token] (JWT) based Bearer authentication with the use of the JWTAuthPlugin. This allows Solr to assert that a user is already authenticated with an external https://en.wikipedia.org/wiki/Identity_provider[Identity Provider] by validating that the JWT  is digitally signed by the Identity Provider. One possible use case is for https://en.wikipedia.org/wiki/OpenID_Connect[OpenID Connect] where a JWT formatted https://en.wikipedia.org/wiki/Access_token[access token] .

== Enable JWT Authentication

To use JWT authentication, you must first create a `security.json` file. This file and where to put it is described in detail in the section <<authentication-and-authorization-plugins.adoc#enable-plugins-with-security-json,Enable Plugins with security.json>>.

The `security.json` file must have an `authentication` part which defines the class being used for authentication along with configuration parameters.

The simplest possible `security.json` for registering the plugin without configuration is:

[source,json]
----
{
  "authentication": {
    "class":"solr.JWTAuthPlugin"
  }
}
----

The plugin will NOT block anonymous traffic in this mode, since the default for `block_unknown` is false. It is then possible to start configuring the plugin using REST calls.

To start enforcing authentication for all users, requiring a valid JWT token in the `Authorization` header, you need to configure the plugin with one or more https://tools.ietf.org/html/rfc7517[JSON Web Key]s (JWK). This is a JSON document containing the key used to sign/encrypt the JWT. It could be a symmetric or asymmetric key. The JWK can either be fetched (and cached) from an external HTTPS endpoint or specified directly in `security.json`. Below is an example of the former:

[source,json]
----
{
  "authentication": {
    "class": "solr.JWTAuthPlugin",
    "blockUnknown": true,
    "jwkUrl": "https://my.key.server/jwk.json"
  }
}
----

The next example shows configuring using https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect Discovery] with a well-konwn URI. 

[source,json]
----
{
  "authentication": {
    "class": "solr.JWTAuthPlugin",
    "blockUnknown": true,
    "wellKnownUrl": "https://idp.example.com/.well-known/openid-configuration"
  }
}
---- 

In this case, `jwk_url` and `iss` will be automatically configured from the fetched configuration.

A more complex configuration with static JWK:

[source,json]
----
{
  "authentication": {
    "class": "solr.JWTAuthPlugin", <1>
    "blockUnknown": true, <2>
    "jwk": { <3>
      "e": "AQAB",
      "kid": "k1",
      "kty": "RSA",
      "n": "3ZF6wBGPMsLzsS1KLghxaVpZtXD3nTLzDm0c974i9-KNU_1rhhBeiVfS64VfEQmP8SA470jEy7yWcvnz9GvG-YAlm9iOwVF7jLl2awdws0ocFjdSPT3SjPQKzOeMO7G9XqNTkrvoFCn1YAi26fbhhcqkwZDoeTcHQdRN32frzccuPhZrwImApIedroKLlKWv2IvPDnz2Bpe2WWVc2HdoWYqEVD3p_BEy8f-RTSHK3_8kDDF9yAwI9jx7CK1_C-eYxXltm-6rpS5NGyFm0UNTZMxVU28Tl7LX8Vb6CikyCQ9YRCtk_CvpKWmEuKEp9I28KHQNmGkDYT90nt3vjbCXxw"
    },
    "clientId": "solr-client-12345", <4>
    "iss": "https://example.com/idp", <5>
    "aud": "https://example.com/solr", <6>
    "principalClaim": "solruid", <7>
    "claimsMatch": { "foo" : "A|B", "dept" : "IT" }, <8>
    "scope": "solr:read solr:write solr:admin", <9>
    "algWhitelist" : [ "RS256", "RS384", "RS512" ] <10>
  }
}
----

Let's comment on this config:

<1> Plugin class
<2> Make sure to block anyone without a valid token
<3> Here we pass the JWK inline instead of referring to a URL with `jwkUrl`
<4> Set the client id registered with Identiy Provider
<5> The issuer claim must match "https://example.com/idp"
<6> The audience claim must match "https://example.com/solr"
<7> Fetch the user id from another claim than the default `sub`
<8> Require that the `roles` claim is one of "A" or "B" and that the `dept` claim is "IT"
<9> Require one of the scopes `solr:read`, `solr:write` or `solr:amin`
<10> Only accept RSA algorithms for signatures

== Configuration parameters

[%header,format=csv,separator=;]
|===
Key              ; Description                                             ; Default
blockUnknown    ; Set to `false` in order to pass requests from unknown users without a token  ; `true`
wellKnownUrl   ; URL to an https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect Discovery] endpoint ; 
clientId        ; Client identifier for use with OpenID Connect           ;
scope            ; Whitespace separate list of valid scopes. If configured, the JWT access token MUST contain a `scope` claim with at least one of the listed scopes. Example: `solr:read solr:admin` ;
jwkUrl          ; An https URL to a https://tools.ietf.org/html/rfc7517[JWK] keys file. Not required if `well_known_url` is provided ; Auto configured if `well_known_url` is provided
jwk              ; As an alternative to `jwk_url` you may provide a JSON object here containing the public key(s) of the issuer.  ; Auto configured if `well_known_url` is provided
iss              ; Validates that `iss` (issuer) equals this string        ; If `well_known_url` is provided, use `issuer` from there.
aud              ; Validates that `aud` (audience) equals this string      ; If `client_id` is configured, require `aud` to match it
requireSub      ; Makes `sub` (subject) mandatory                         ; `true`
requireExp      ; Makes `exp` (expiry time) mandatory                     ; `true`
algWhitelist    ; JSON array with algorithms to accept: `HS256`, `HS384`, `HS512`, `RS256`, `RS384`, `RS512`, `ES256`, `ES384`, `ES512`, `PS256`, `PS384`, `PS512`, `none  ; 
jwkCacheDur    ; Duration of JWK cache in seconds                        ; `3600` (1 hour)
principalClaim  ; What claim id to pull principal from                    ; `sub`
claimsMatch     ; JSON object of claims (key) that must match a regular expression (value). Example: `{ "foo" : "A|B" }` will require the `foo` claim to be either "A" or "B". ; (none)
|===


== Editing Authentication Plugin Configuration

All properties mentioned above can be set or changed using the <<basic-authentication-plugin.adoc#editing-authentication-plugin-configuration,Config Edit API>>. You can thus start with a simple configuration with only `class` configured and then configure the rest using the API.

=== Set a Property

Set properties for the authentication plugin. Each of the configuration keys in the table above can be used as parameter keys for the `set-property` command.

Example:

[.dynamic-tabs]
--
[example.tab-pane#v1set-property]
====
[.tab-label]*V1 API*

[source,bash]
----
curl --user solr:SolrRocks http://localhost:8983/solr/admin/authentication -H 'Content-type:application/json' -d  '{"set-property": {"blockUnknown":true, "wellKnownUrl": "https://example.com/.well-knwon/openid-configuration", "scope": "solr:read solr:write"}}'
----
====

[example.tab-pane#v2set-property]
====
[.tab-label]*V2 API*

[source,bash]
----
curl --user solr:SolrRocks http://localhost:8983/api/cluster/security/authentication -H 'Content-type:application/json' -d  '{"set-property": {"blockUnknown":true, "wellKnownUrl": "https://example.com/.well-knwon/openid-configuration", "scope": "solr:read solr:write"}}'
----
====
--

== Using clients with JWT Auth 

=== SolrJ

SolrJ does not currently support setting JWT tokens per request. This is planned for a future release.

=== cURL

To authenticate with Solr with cURL

=== Admin UI 

The Admin UI runs as a SPA (single page application) in your browser, and talks with the Solr APIs just like any other client. Because of this the Admin UI will stop working after enabling this plugin. To circumvent this you can install a browser plugin that adds HTTP headers to requests, and add a valid JWT token to the `Authorization` header by hand. 

== Using the Solr Control Script with Basic Auth

The control script (`bin/solr`) does not currently support JWT Auth.