= JWT Authentication Plugin
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr can support https://en.wikipedia.org/wiki/JSON_Web_Token[JSON Web Token] (JWT) based Bearer authentication for users with the use of the JWTAuthPlugin. This allows Solr to assert that a user is already authenticated with an external service by validating that the JWT  is digitally signed by the Identity service. One possible use case is for https://en.wikipedia.org/wiki/OpenID_Connect[OpenID Connect].

== Enable JWT Authentication

To use JWT authentication, you must first create a `security.json` file. This file and where to put it is described in detail in the section <<authentication-and-authorization-plugins.adoc#enable-plugins-with-security-json,Enable Plugins with security.json>>.

The `security.json` file must have an `authentication` part which defines the class being used for authentication along with configuration parameters.

The simplest possible `security.json` for registering the plugin without configuration is:

[source,json]
----
{
  "authentication": {
    "class":"solr.JWTAuthPlugin"
  }
}
----

The plugin will NOT block anonymous traffic in this mode, since the default for `block_unknown` is false. It is then possible to start configuring the plugin using REST calls.

To start enforcing authentication for all users, requiring a valid JWT token in the `Authorization` header, you need to configure the plugin with one or more https://tools.ietf.org/html/rfc7517[JSON Web Key]s (JWK). This is a JSON document containing the key used to sign/encrypt the JWT. It could be a symmetric or asymmetric key. The JWK can either be fetched (and cached) from an external HTTPS endpoint or specified directly in `security.json`. Below is an example of the former:

[source,json]
----
{
  "authentication": {
    "class": "solr.JWTAuthPlugin",
    "block_unknown": true,
    "jwk_url": "https://my.key.server/jwk.json"
  }
}
----

The next example shows configuring using https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect Discovery] with a well-konwn URI. 

[source,json]
----
{
  "authentication": {
    "class": "solr.JWTAuthPlugin",
    "block_unknown": true,
    "well_known_url": "https://my.key.server/.well-known/openid-configuration"
  }
}
---- 

In this case, `jwk_url` and `iss` will be automatically configured from the fetched configuration.

A more complex configuration with static JWK:

[source,json]
----
{
  "authentication": {
    "class": "solr.JWTAuthPlugin", <1>
    "block_unknown": true, <2>
    "jwk": { <3>
      "e": "AQAB",
      "kid": "k1",
      "kty": "RSA",
      "n": "3ZF6wBGPMsLzsS1KLghxaVpZtXD3nTLzDm0c974i9-KNU_1rhhBeiVfS64VfEQmP8SA470jEy7yWcvnz9GvG-YAlm9iOwVF7jLl2awdws0ocFjdSPT3SjPQKzOeMO7G9XqNTkrvoFCn1YAi26fbhhcqkwZDoeTcHQdRN32frzccuPhZrwImApIedroKLlKWv2IvPDnz2Bpe2WWVc2HdoWYqEVD3p_BEy8f-RTSHK3_8kDDF9yAwI9jx7CK1_C-eYxXltm-6rpS5NGyFm0UNTZMxVU28Tl7LX8Vb6CikyCQ9YRCtk_CvpKWmEuKEp9I28KHQNmGkDYT90nt3vjbCXxw"
    },
    "client_id": "solr-client-12345", <4>
    "iss": "https://example.com/idp", <5>
    "aud": "https://example.com/solr", <6>
    "principal_claim": "solruid", <7>
    "claims_match": { "roles" : "admin|search", "dept" : "IT" }, <8>
    "scope": "solr:read solr:write solr:admin", <9>
    "alg_whitelist" : [ "RS256", "RS384", "RS512" ] <10>
  }
}
----

Let's comment on this config:

<1> Plugin class
<2> Make sure to block anyone without a valid token
<3> Here we pass the JWK inline instead of referring to a URL with `jwk_url`
<4> Set the client id registered with Identiy Provider
<5> The issuer claim must match "https://example.com/idp"
<6> The audience claim must match "https://example.com/solr"
<7> Fetch the user id from another claim than the default `sub`
<8> Require that the `roles` claim is one of "admin" or "search" and that the `dept` claim is "IT"
<9> Require one of the scopes `solr:read`, `solr:write` or `solr:amin`
<10> Only accept RSA algorithms for signatures

== Configuration parameters

[%header,format=csv,separator=;]
|===
Key              ; Description                                             ; Default
block_unknown    ; Set to `false` in order to pass requests from unknown users without a token  ; `true`
well_known_url   ; URL to an https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect Discovery] endpoint ; 
client_id        ; Client identifier for use with OpenID Connect           ;
scope            ; Whitespace separate list of valid scopes. If configured, the JWT access token MUST contain a `scope` claim with at least one of the listed scopes. Example: `solr:read solr:admin` ;
jwk_url          ; An https URL to a https://tools.ietf.org/html/rfc7517[JWK] keys file. Not required if `well_known_url` is provided ; Auto configured if `well_known_url` is provided
jwk              ; As an alternative to `jwk_url` you may provide a JSON object here containing the public key(s) of the issuer.  ; Auto configured if `well_known_url` is provided
iss              ; Validates that `iss` (issuer) equals this string        ; If `well_known_url` is provided, use `issuer` from there.
aud              ; Validates that `aud` (audience) equals this string      ; If `client_id` is configured, require `aud` to match it
require_sub      ; Makes `sub` (subject) mandatory                         ; `true`
require_exp      ; Makes `exp` (expiry time) mandatory                     ; `true`
alg_whitelist    ; JSON array with algorithms to accept: `HS256`, `HS384`, `HS512`, `RS256`, `RS384`, `RS512`, `ES256`, `ES384`, `ES512`, `PS256`, `PS384`, `PS512`, `none  ; 
jwk_cache_dur    ; Duration of JWK cache in seconds                        ; `3600` (1 hour)
principal_claim  ; What claim id to pull principal from                    ; `sub`
claims_match     ; JSON object of claims (key) that must match a regular expression (value). Example: `{ "roles" : "A|B" }` will require the `roles` claim to be either "A" or "B". ; (none)
|===


== Editing Authentication Plugin Configuration

**TODO: This plugin currently does not support edit API.**

=== Using JWT Auth with SolrJ

To use JWT Auth with SolrJ you must configure a `SolrHttpClientBuilder` that sets the `Authorization: Bearer` header. How to obtain a valid JWT token is up to the client application to choose.

**TODO: Describe this **

=== Using the Solr Control Script with Basic Auth

The control scripts (`bin/solr`) do not currently support JWT Auth.