= MBean Request Handler
:page-shortname: mbean-request-handler
:page-permalink: mbean-request-handler.html

The MBean Request Handler offers programmatic access to the information provided on the <<plugins-stats-screen.adoc#plugins-stats-screen,Plugin/Stats>> page of the Admin UI.

The MBean Request Handler accepts the following parameters:

// TODO: Change column width to %autowidth.spread when https://github.com/asciidoctor/asciidoctor-pdf/issues/599 is fixed

[cols="10,20,10,60",options="header"]
|===
|Parameter |Type |Default |Description
|key |multivalued |all |Restricts results by object key.
|cat |multivalued |all |Restricts results by category name.
|stats |boolean |false |Specifies whether statistics are returned with results. You can override the `stats` parameter on a per-field basis.
|wt |multivalued |xml |The output format. This operates the same as the <<response-writers.adoc#response-writers,`wt` parameter in a query>>.
|===

[[MBeanRequestHandler-Examples]]
== Examples

The following examples assume you are running Solr's `techproducts` example configuration:

[source,bash]
----
bin/solr start -e techproducts
----

To return information about the CACHE category only:

`\http://localhost:8983/solr/techproducts/admin/mbeans?cat=CACHE`

To return information and statistics about the CACHE category only, formatted in JSON:

`\http://localhost:8983/solr/techproducts/admin/mbeans?stats=true&cat=CACHE&indent=true&wt=json`

To return information for everything, and statistics for everything except the `fieldCache`:

`\http://localhost:8983/solr/techproducts/admin/mbeans?stats=true&f.fieldCache.stats=false`

To return information and statistics for the `fieldCache` only:

`\http://localhost:8983/solr/techproducts/admin/mbeans?key=fieldCache&stats=true`
