= MBean Request Handler
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

The MBean Request Handler offers programmatic access to the information provided on the <<plugins-stats-screen.adoc#,Plugin/Stats>> page of the Admin UI.

The MBean Request Handler accepts the following parameters:

`key`::
Restricts results by object key.

`cat`::
Restricts results by category name.

`stats`::
Specifies whether statistics are returned with results. You can override the `stats` parameter on a per-field basis. The default is `false`.

`wt`::
The output format. This operates the same as the <<response-writers.adoc#,`wt` parameter in a query>>. The default is `json`.

== MBeanRequestHandler Examples

// TODO 7.1 - replace with link to tutorial
The following examples assume you are running Solr's `techproducts` example configuration:

[source,bash]
----
bin/solr start -e techproducts
----

To return information about the CACHE category only:

[source,text]
http://localhost:8983/solr/techproducts/admin/mbeans?cat=CACHE

To return information and statistics about the CACHE category only, formatted in XML:

[source,text]
http://localhost:8983/solr/techproducts/admin/mbeans?stats=true&cat=CACHE&wt=xml

To return information for everything, and statistics for everything except the `fieldCache`:

[source,text]
http://localhost:8983/solr/techproducts/admin/mbeans?stats=true&f.fieldCache.stats=false

To return information and statistics for the `fieldCache` only:

[source,text]
http://localhost:8983/solr/techproducts/admin/mbeans?key=fieldCache&stats=true
