= Searching
:page-children: overview-of-searching-in-solr, +
  velocity-search-ui, +
  relevance, +
  query-syntax-and-parsing, +
  json-request-api, +
  json-facet-api, +
  faceting, +
  highlighting, +
  spell-checking, +
  query-re-ranking, +
  transforming-result-documents, +
  searching-nested-documents, +
  suggester, +
  morelikethis, +
  pagination-of-results, +
  collapse-and-expand-results, +
  result-grouping, +
  spatial-search, +
  the-terms-component, +
  the-term-vector-component, +
  the-stats-component, +
  the-query-elevation-component, +
  the-tagger-handler, +
  response-writers, +
  near-real-time-searching, +
  realtime-get, +
  exporting-result-sets, +
  parallel-sql-interface, +
  analytics

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

This section describes how Solr works with search requests. It covers the following topics:

* <<overview-of-searching-in-solr.adoc#,Overview of Searching in Solr>>: An introduction to searching with Solr.
* <<velocity-search-ui.adoc#,Velocity Search UI>>: A simple search UI using the VelocityResponseWriter.
* <<relevance.adoc#,Relevance>>: Conceptual information about understanding relevance in search results.
* <<query-syntax-and-parsing.adoc#,Query Syntax and Parsing>>: A brief conceptual overview of query syntax and parsing. It also contains the following sub-sections:
** <<common-query-parameters.adoc#,Common Query Parameters>>: No matter the query parser, there are several parameters that are common to all of them.
** <<the-standard-query-parser.adoc#,The Standard Query Parser>>: Detailed information about the standard Lucene query parser.
** <<the-dismax-query-parser.adoc#,The DisMax Query Parser>>: Detailed information about Solr's DisMax query parser.
** <<the-extended-dismax-query-parser.adoc#,The Extended DisMax Query Parser>>: Detailed information about Solr's Extended DisMax (eDisMax) Query Parser.
** <<function-queries.adoc#,Function Queries>>: Detailed information about parameters for generating relevancy scores using values from one or more numeric fields.
** <<local-parameters-in-queries.adoc#,Local Parameters in Queries>>: How to add local arguments to queries.
** <<other-parsers.adoc#,Other Parsers>>: More parsers designed for use in specific situations.
* <<json-request-api.adoc#,JSON Request API>>: Overview of Solr's JSON Request API.
** <<json-query-dsl.adoc#,JSON Query DSL>>: Detailed information about a simple yet powerful query language for JSON Request API.
* <<json-facet-api.adoc#facet-analytics-module,JSON Facet API>>: Overview of Solr's JSON Facet API.
* <<faceting.adoc#,Faceting>>: Detailed information about categorizing search results based on indexed terms.
* <<highlighting.adoc#,Highlighting>>: Detailed information about Solr's highlighting capabilities, including multiple underlying highlighter implementations.
* <<spell-checking.adoc#,Spell Checking>>: Detailed information about Solr's spelling checker.
* <<query-re-ranking.adoc#,Query Re-Ranking>>: Detailed information about re-ranking top scoring documents from simple queries using more complex scores.
** <<learning-to-rank.adoc#,Learning To Rank>>: How to use LTR to run machine learned ranking models in Solr.

* <<transforming-result-documents.adoc#,Transforming Result Documents>>: Detailed information about using `DocTransformers` to add computed information to individual documents
* <<searching-nested-documents.adoc#,Searching Nested Documents>>: Detailed information about constructing nested and hierarchical queries.
* <<suggester.adoc#,Suggester>>: Detailed information about Solr's powerful autosuggest component.
* <<morelikethis.adoc#,MoreLikeThis>>: Detailed information about Solr's similar results query component.
* <<pagination-of-results.adoc#,Pagination of Results>>: Detailed information about fetching paginated results for display in a UI, or for fetching all documents matching a query.
* <<result-grouping.adoc#,Result Grouping>>: Detailed information about grouping results based on common field values.
* <<spatial-search.adoc#,Spatial Search>>: How to use Solr's spatial search capabilities.
* <<the-terms-component.adoc#,The Terms Component>>: Detailed information about accessing indexed terms and the documents that include them.
* <<the-term-vector-component.adoc#,The Term Vector Component>>: How to get term information about specific documents.
* <<the-stats-component.adoc#,The Stats Component>>: How to return information from numeric fields within a document set.
* <<the-query-elevation-component.adoc#,The Query Elevation Component>>: How to force documents to the top of the results for certain queries.
* <<the-tagger-handler.adoc#,The Tagger Handler>>: The SolrTextTagger, for basic named entity tagging in text.
* <<response-writers.adoc#,Response Writers>>: Detailed information about configuring and using Solr's response writers.
* <<near-real-time-searching.adoc#,Near Real Time Searching>>: How to include documents in search results nearly immediately after they are indexed.
* <<realtime-get.adoc#,RealTime Get>>: How to get the latest version of a document without opening a searcher.
* <<exporting-result-sets.adoc#,Exporting Result Sets>>: Functionality to export large result sets out of Solr.
* <<parallel-sql-interface.adoc#,Parallel SQL Interface>>: An interface for sending SQL statements to Solr, and using advanced parallel query processing and relational algebra for complex data analysis.
* <<analytics.adoc#,The Analytics Component>>: A framework to compute complex analytics over a result set.
