= Synchronized Disruption API
:page-toclevels: 2
:page-tocclass: right
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

The Synchronized Disruption API is used to manage disruptions across the cluster. All calls will be through the "/admin/sychronizeddisruption" handler.

== List API

The List API will list all disruptions from the instance that the request is directed towards.

=== List API Example

The output will contain all disruptions, their, name, their class, and their cron schedule.

*Input*

[source,text]
----
http://localhost:8983/solr/admin/synchronizeddisruption?action=list
----

*Output*

[source,json]
----
{
  "responseHeader":{
    "status":0,
    "QTime":2931},
  "disruptions":["Name: test, Class: class org.apache.solr.cloud.synchronizeddisruption.GarbageCollection, Cron: 30 * * * * ?"]}
----

== Remove API

The Remove API will remove a disruption by name.

=== Remove API Parameters

The Remove action requires the following parameters:

`name`::
The name of the disruption to be removed.

=== Remove API Example

*Input*

[source,text]
----
http://localhost:8983/solr/admin/synchronizeddisruption?action=remove&name=test
----

*Output*

[source,json]
----
{
  "responseHeader":{
    "status":0,
    "QTime":3191},
  "removedDisruptions":{
    "http://127.0.0.1:8984/solr":"test2 has be closed with success value of true",
    "http://127.0.0.1:8983/solr":"test2 has be closed with success value of true"}}
----

== Add API

The Add API will add a disruption to the cluster.

=== Add API Parameters

The Add action requires the following parameters:

`name`::
The name of the disruption to be created.

`class`::
The full class name of the class to be loaded.

`cron`::
The cron expression to be used to schedule the disruption.  Note that the cron syntax follows the https://logging.apache.org/log4j/2.x/log4j-core/apidocs/org/apache/logging/log4j/core/util/CronExpression.html[Log4J CronExpression rules, role="external", window="_blank"], which vary slightly from normal cron syntax.

=== Add API Example

*Input*

[source,text]
----
http://localhost:8983/solr/admin/synchronizeddisruption?action=add&name=test&class=org.apache.solr.cloud.synchronizeddisruption.GarbageCollection&cron=30%20*%20*%20*%20*%20?
----

*Output*

[source,json]
----
{
  "responseHeader":{
    "status":0,
    "QTime":2748},
  "addedDisruptions":{
    "http://127.0.0.1:8984/solr":"test has be added with success value of true",
    "http://127.0.0.1:8983/solr":"test has be added with success value of true"}}
----