/* Generated By:JavaCC: Do not edit this line. HTMLParserConstants.java */
package org.apache.lucene.demo.html;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HTMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ScriptStart = 1;
  /** RegularExpression Id. */
  int TagName = 2;
  /** RegularExpression Id. */
  int DeclName = 3;
  /** RegularExpression Id. */
  int Comment1 = 4;
  /** RegularExpression Id. */
  int Comment2 = 5;
  /** RegularExpression Id. */
  int Word = 6;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int HEX = 9;
  /** RegularExpression Id. */
  int Entity = 10;
  /** RegularExpression Id. */
  int Space = 11;
  /** RegularExpression Id. */
  int SP = 12;
  /** RegularExpression Id. */
  int Punct = 13;
  /** RegularExpression Id. */
  int ScriptText = 14;
  /** RegularExpression Id. */
  int ScriptEnd = 15;
  /** RegularExpression Id. */
  int ArgName = 16;
  /** RegularExpression Id. */
  int ArgEquals = 17;
  /** RegularExpression Id. */
  int TagEnd = 18;
  /** RegularExpression Id. */
  int ArgValue = 19;
  /** RegularExpression Id. */
  int ArgQuote1 = 20;
  /** RegularExpression Id. */
  int ArgQuote2 = 21;
  /** RegularExpression Id. */
  int Quote1Text = 23;
  /** RegularExpression Id. */
  int CloseQuote1 = 24;
  /** RegularExpression Id. */
  int Quote2Text = 25;
  /** RegularExpression Id. */
  int CloseQuote2 = 26;
  /** RegularExpression Id. */
  int CommentText1 = 27;
  /** RegularExpression Id. */
  int CommentEnd1 = 28;
  /** RegularExpression Id. */
  int CommentText2 = 29;
  /** RegularExpression Id. */
  int CommentEnd2 = 30;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinScript = 1;
  /** Lexical state. */
  int WithinTag = 2;
  /** Lexical state. */
  int AfterEquals = 3;
  /** Lexical state. */
  int WithinQuote1 = 4;
  /** Lexical state. */
  int WithinQuote2 = 5;
  /** Lexical state. */
  int WithinComment1 = 6;
  /** Lexical state. */
  int WithinComment2 = 7;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<script\"",
    "<TagName>",
    "<DeclName>",
    "\"<!--\"",
    "\"<!\"",
    "<Word>",
    "<LET>",
    "<NUM>",
    "<HEX>",
    "<Entity>",
    "<Space>",
    "<SP>",
    "<Punct>",
    "<ScriptText>",
    "<ScriptEnd>",
    "<ArgName>",
    "\"=\"",
    "<TagEnd>",
    "<ArgValue>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<token of kind 22>",
    "<Quote1Text>",
    "<CloseQuote1>",
    "<Quote2Text>",
    "<CloseQuote2>",
    "<CommentText1>",
    "\"-->\"",
    "<CommentText2>",
    "\">\"",
  };

}
