/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package org.apache.lucene.queryparser.surround.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _NUM_CHAR = 1;
  /** RegularExpression Id. */
  int _TERM_CHAR = 2;
  /** RegularExpression Id. */
  int _WHITESPACE = 3;
  /** RegularExpression Id. */
  int _STAR = 4;
  /** RegularExpression Id. */
  int _ONE_CHAR = 5;
  /** RegularExpression Id. */
  int _DISTOP_NUM = 6;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int W = 11;
  /** RegularExpression Id. */
  int N = 12;
  /** RegularExpression Id. */
  int LPAREN = 13;
  /** RegularExpression Id. */
  int RPAREN = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int CARAT = 17;
  /** RegularExpression Id. */
  int TRUNCQUOTED = 18;
  /** RegularExpression Id. */
  int QUOTED = 19;
  /** RegularExpression Id. */
  int SUFFIXTERM = 20;
  /** RegularExpression Id. */
  int TRUNCTERM = 21;
  /** RegularExpression Id. */
  int TERM = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;

  /** Lexical state. */
  int Boost = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<_NUM_CHAR>",
    "<_TERM_CHAR>",
    "<_WHITESPACE>",
    "\"*\"",
    "\"?\"",
    "<_DISTOP_NUM>",
    "<token of kind 7>",
    "<OR>",
    "<AND>",
    "<NOT>",
    "<W>",
    "<N>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\"^\"",
    "<TRUNCQUOTED>",
    "<QUOTED>",
    "<SUFFIXTERM>",
    "<TRUNCTERM>",
    "<TERM>",
    "<NUMBER>",
  };

}
