= Ref Guide Publication Process
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.


This section details how to build the Guide for publication.

== Pre-Requisites

* You have checked out the Lucene/Solr source code on the machine you will be doing the release from.
* You have Subversion installed. This is needed for committing the HTML files to the production website repo.
* You have installed Ruby and several gems described in the README file located at `solr/solr-ref-guide/README.adoc` in your Lucene/Solr checkout.

NOTE: Builds are available via Jenkins for several branches. However, these HTML pages will have the `DRAFT` status noted in them and will not be suitable for publishing.

== Build the Guide

The build process generates the page hierarchy and builds the HTML pages with custom templates the Lucene/Solr project has defined.

To build the HTML:

. Navigate to `./solr/solr-ref-guide`, where the Guide's `build.xml` is located.
. Run:
+
[source,bash]
$ ant clean build-site -Dsolr-guide-version=X.Y
+
where `X.Y` is the version you want to publish (i.e., `7.4`).
. The resulting Guide will be in `solr/build/solr-ref-guide`. The HTML files themselves will be in `solr/build/solr-ref-guide/html-site`.

IMPORTANT: The `-Dsolr-guide-version` system property is optional if you build drafts locally (i.e., not for publication). By default the build system uses the `lucene/version.properties` file in the current branch and assumes this is a `DRAFT` build which will have a DRAFT watermark and other labels on the pages. Including the `-Dsolr-guide-version` system property ensures the DRAFT watermark and labels are removed from the HTML files.

== Upload to the Website

// A lot of this was copied from https://wiki.apache.org/lucene-java/ReleaseTodo#Website_.2B-.3D_javadocs. See that section for explanations for why some steps are required.

=== Step 1: Update extpaths.txt in CMS Staging

. Checkout CMS trunk:
+
[source,bash]
$ svn co --depth=immediates https://svn.apache.org/repos/asf/lucene/cms/trunk/content website-source
+
* If you already have this repo checked out, you can simply `svn up website-source` to update to the latest revision.
. `$ cd website-source` (where you just checked out the repo)
. Add the path for the new Guide version:
+
[source,bash]
$ echo solr/guide/X_Y >> extpaths.txt
+
where `X_Y` is the new version (i.e, `8_2`)
. Commit changes:
+
[source,bash]
$ svn commit -m "Update CMS production sync exceptions for X_Y_Z Guide" extpaths.txt

=== Step 2: Push Guide to Website Production

Go to the checkout directory where you have built the Guide and push the documentation via Subversion `import`. You must push it to the path you just added to `extpaths.txt`, so if the path you added was `solr/guide/7_7`, you'll use the path as shown in the below example:

[source,bash]
svn -m "Add Ref Guide for Solr 7.7" import <checkoutroot>/solr/build/solr-ref-guide/html-site https://svn.apache.org/repos/infra/websites/production/lucene/content/solr/guide/6_5

Confirm you can browse to these URLs manually, and especially that Solr javadocs link back to Lucene's correctly. Example:
https://lucene.apache.org/solr/guide/7_7

=== Step 3: Push Staging extpaths.txt to Production

The `extpaths.txt` works by listing paths that should be ignored when the CMS syncs the staging and production repositories. Publishing staging to production will only succeed if the paths listed in `extpaths.txt` exist in production. At the same time, if a path exists in production but not in staging it will be deleted unless it is defined in `extpaths.txt`.

After pushing the content to production, check that the `extpaths.txt` in production includes the proper path to ensure that the Guide is not deleted incorrectly. If it does not exist in production, try to publish the site again to make sure it is updated.

Production URL: https://lucene.apache.org/extpaths.txt

== Publish the Guide

=== Make New HTML Version the Default

There are a few steps to take to make the new HTML version the default.

TIP: You can use the CMS system for these changes, or you can edit the file locally and commit it to the staging repo.

. Update the landing page at https://lucene.apache.org/solr/guide (the file is at `content/solr/guide/index.mdtext` in SVN) to link to the newest version.
. Update the Guide redirect rule that looks like the below in `content/.htaccess` so URLs without a version in the path are redirected to the latest available version.
+
[source,text]
RedirectMatch temp /solr/guide/(?!index.html)([a-z].*) /solr/guide/7_0/$1
+
In the above example, you would change the `7_0` part of the path to the right version (`7_1`, etc.).

== Announce the Release

If the Guide is being released separately from the main artifacts,
announce the release on `solr-user@lucene.apache.org` so users are aware it is available.

If the Guide is being published more than a day or two after the application itself, you could also update the Solr website news page with the announcement (https://lucene.apache.org/solr/news.html).

== Updating HTML Files after Publication

To re-publish an existing online version of the Guide, you will need to
checkout the directory in production website repository and overwrite the
existing files:

. Build the new HTML files locally (`ant clean build-site`). This requires the same <<Pre-Requisites,pre-requisites>> from above.
. Checkout the directory you need to update from the production repo: `svn co https://svn.apache.org/repos/infra/websites/production/lucene/content/solr/guide/<dir>`.
* This command checks out the Guide version directory into a local subdirectory with the same name as the version (such as "6_5"). You can provide a better name locally if you prefer by adding it to the end of the command shown above.
* Don't shortcut this and download the whole production website. It will take an incredibly long time and that will feel like _forever_.
. Copy the files from the build location to the checked out Guide directory. For example, if we needed to replace the Guide for Solr 7.7, we'd do `cp -r ./solr/build/solr-ref-guide/html-site 7_7/.`
. Use `svn status` to see the files modified.
. If there are any pages added or deleted, use `svn add <file>` or `svn rm <file>` as needed.
. Commit the changes: `svn commit -m "Update production 7.7 Ref Guide"`
