name: Ant precommit

on:
  pull_request:
    branches:
      - 'branch_8_11'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Ivy packages
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache/
          key: ${{ runner.os }}-ant-precommit-${{ hashFiles('**/ivy-versions.properties') }}
          restore-keys: |
            ${{ runner.os }}-ant-precommit-
            ${{ runner.os }}-ant-

      - name: Ivy bootstrap
        run: ant ivy-bootstrap

      - name: Precommit
        run: ant precommit
