name: SonarQube

on:
  push:
    branches:
      - branch_8_3
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarqube:
    uses: Unity-Technologies/github-actions-workflows/.github/workflows/sonarqube.yml@main
    with:
      coverage: false